### ISSUE TITLE
Palindrome sentence

### ISSUE THREAD

**Issue by kevinccbsg** [kevinccbsg/ohce-kata#2]
We have to check this requirement. As we have to remove any character that is NOT a letter or number to get this thing ready. 😄 

<img width="724" alt="Captura de pantalla 2019-12-13 a las 11 42 32" src="https://user-images.githubusercontent.com/12685053/70794827-dbecf800-1d9e-11ea-9f95-f3b24cb61b31.png">

**Comment by ismaelocaramelo** [comment]
Close: https://github.com/kevinccbsg/ohce-kata/pull/3
